spring:
  profiles:
    actice: dev #激活开发环境配置
---
server:
  port: 32232  #端口
spring:
  profiles: dev  #开发环境
  applications:
    name: microservice-cloud-eureka-one
eureka:
  instance:
    hostname: eureka32232.com #eureka 服务端的实例名称
  client:
    register-with-eureka: false #服务注册 false 表示不向eureka 服务注册自己
    fetch-registry: false #服务发现 false 表示自己不从eureka 服务中获取注册信息
    service-url: #eureka 客户端与eureka 服务端的交互地址，集群版配置对方的地址   单机版配置自己的信息
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群版
      defaultZone: http://eureka32231.com:32231/eureka/
  server: # eureka  自我保护机制关闭（默认开启）
    enable-self-preservation: false
---
server:
  port: 32232 #端口
spring:
  profiles: pord  #生产环境
  applications:
    name: microservice-cloud-eureka-one
eureka:
  instance:
    hostname: eureka32232.com #eureka 服务端的实例名称
  client:
    register-with-eureka: false #服务注册 false 表示不向eureka 服务注册自己
    fetch-registry: false #服务发现 false 表示自己不从eureka 服务中获取注册信息
    service-url: #eureka 客户端与eureka 服务端的交互地址，集群版配置对方的地址   单机版配置自己的信息
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群版
      defaultZone: http://eureka32231.com:32231/eureka/
  server: # eureka  自我保护机制关闭（默认开启）
    enable-self-preservation: true