spring:
 profiles:
  active: dev
---

server:
 port: 50001
spring:
 profiles: dev
  application:
   name: microservice-cloud-config-dev
---
server:
 port: 50002
spring:
 profiles: test
  application:
   name: microservice-cloud-config-test
