spring:
  profiles:
    active: dev
---
server:
  port: 32332
spring:
  profiles: dev
  application:
    name: microservice-consumer-product-feign
  kafka:
    consumer:
      bootstrap-servers: 119.3.0.139:9092
      group-id: test-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#eureka 配置
eureka:
  client:
    register-with-eureka: true  #是否向注册中心注册
    fetch-registry: true #是否获取其他服务的信息
    service-url: #eureka 注册中心的地址，需要注册到哪一个注册中心
      #defaultZone: http://localhost:32233/eureka
      defaultZone: http://eureka32231.com:32231/eureka,http://eureka32232.com:32232/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 访问路径就会显示为IP
feign:
  hystrix:
    enabled: true #开启服务熔断器
---
server:
  port: 32332
spring:
  profiles: prod
  application:
    name: microservice-consumer-product-feign
  kafka:
    consumer:
      bootstrap-servers: 119.3.0.139:9092
      group-id: test-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#eureka 配置
eureka:
  client:
    register-with-eureka: false  #是否向注册中心注册
    fetch-registry: true #是否获取其他服务的信息
    service-url: #eureka 注册中心的地址，需要注册到哪一个注册中心
      #defaultZone: http://localhost:32233/eureka
      defaultZone: http://119.3.0.139/eureka,http://119.3.0.139:32232/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true # 访问路径就会显示为IP
feign:
  hystrix:
    enabled: true #开启服务熔断器