#注意，如果在记事本上面进行编辑，下面你的缩进不能使用tab 键，否则报错   
server:
  port: 55655
  
spring:
  profiles:
    active: dev


spring:
  profiles: dev #开发环境dev
   applications:
     name: microservice-cloud-config-dev

server:
  port: 55655

spring:
  profiles: test #测试环境test
   applications:
     name: microservice-cloud-config-test